<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <LangVersion>12.0</LangVersion>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <StaticWebAssetBasePath>/</StaticWebAssetBasePath>
  </PropertyGroup>

  <PropertyGroup>
    <VersionPrefix>13.0.5</VersionPrefix>
    <VersionSuffix Condition="'$(Configuration)'=='Debug'">build$([System.DateTime]::UtcNow.ToString(`yyyyMMddHHmm`))</VersionSuffix>
    <Authors>Anders Bjerner</Authors>
    <Company>Limbo</Company>
    <Product>Skybrud.Essentials</Product>
    <Description>Skybrud.Essentials addon for working with Umbraco 13.</Description>
    <Copyright>Copyright © $([System.DateTime]::UtcNow.ToString(`yyyy`))</Copyright>
  </PropertyGroup>

  <!-- Information for the NuGet package -->
  <PropertyGroup>
    <PackageId>Skybrud.Essentials.Umbraco</PackageId>
    <PackageTags>Skybrud, Limbo, Essentials, Umbraco, Extensions, Umbraco-Marketplace</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://packages.limbo.works/skybrud.essentials.umbraco/</PackageProjectUrl>
    <PackageIcon>Limbo.png</PackageIcon>
    <PackageReadmeFile>NUGET.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/skybrud/Skybrud.Essentials.Umbraco</RepositoryUrl>
  </PropertyGroup>

  <!-- Include additional metadata in the assembly -->
  <ItemGroup>
    <AssemblyMetadata Include="PackageProjectUrl" Value="https://packages.limbo.works/skybrud.essentials.umbraco/" />
    <AssemblyMetadata Include="DocumentationUrl" Value="https://packages.limbo.works/skybrud.essentials.umbraco/docs/v13/" />
    <AssemblyMetadata Include="NuGetUrl" Value="https://www.nuget.org/packages/Skybrud.Essentials.Umbraco" />
    <AssemblyMetadata Include="UmbracoMarketplaceUrl" Value="https://marketplace.umbraco.com/package/skybrud.essentials.umbraco" />
  </ItemGroup>

  <!-- Include NuGet dependencies -->
  <ItemGroup>
    <PackageReference Include="Skybrud.Essentials" Version="1.1.60" />
    <PackageReference Include="Umbraco.Cms.Core" Version="[13.0.0,13.999)" NoWarn="NU1902,NU1903" />
    <PackageReference Include="Umbraco.Cms.Web.Website" Version="[13.0.0,13.999)" NoWarn="NU1902,NU1903" />
    <PackageReference Include="Umbraco.Cms.Web.BackOffice" Version="[13.0.0,13.999)" NoWarn="NU1902,NU1903" />
  </ItemGroup>

  <!-- Include package icon for NuGet package -->
  <ItemGroup>
    <Content Include="../build/Limbo.png" Pack="true" PackagePath="\" />
    <None Include="..\..\NUGET.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <!-- Exclude internal files from the NuGet package -->
  <ItemGroup>
    <Content Remove="compilerconfig.json" />
    <None Include="compilerconfig.json" />
  </ItemGroup>

  <!-- Generate XML documentation -->
  <PropertyGroup>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>

</Project>